name: Tests
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Install Clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          bb: '1.12.196'
          cli: 1.10.1.693              # Clojure CLI based on tools.deps

      - name: Run tests
        run: ./gradlew test
